spring:
  datasource:
    url: jdbc:mysql://114.55.93.214:3306/platform?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Scy@123456789
    type: com.alibaba.druid.pool.DruidDataSource

    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=50

#整合mybatis
mybatis:
  type-aliases-package: com.sun.entity
  mapper-locations: classpath:/mapper/*.xml

